spring:
  datasource:
    username: root
    password: 1122
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/users
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com